server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: customer-service

zipkin:
  base-url: http://172.21.20.124:9411


