spring:
  zipkin:
    base-url: http://172.21.20.124:9411
  cloud:
    config:
      uri: http://localhost:8888
      allow-override: true
      override-none: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 0


eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
   org:
    springframework: DEBUG





