spring:
  cloud:
    config:
      allow-override: true
      override-none: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


cloud:
  config:
    uri: http://localhost:8888
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zipkin:
  base-url: http://172.21.20.124:9411



