customer-service:
 version: 123

spring:
 application:
  name: customer-service
 config:
  import: 'configserver:'
 cloud:
  config:
   name: customer-service,config-client
cloud:
 config:
  uri: http://localhost:8888
server:
 port: 0

eureka:
 instance:
  instance-id: ${spring.application.name}:${instanceId:${random.value}}
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/

zipkin:
 base-url: http://172.21.20.124:9411

version: 12

