service-ry:
 version: 12

inventory-service:
  version: 12

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/inventory?useSSL=false&serverTimezone=GMT
    usernam: root
    passwor: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


  server:
    error:
      include-message: always
      include-binding-errors: always

axon:
  eventhandling:
    processors:
      inventory-group:
        mode: subscribing
  axonserver:
    servers: "localhost:8124"

networks:
  - estore

logging:
  level:
    org:
      axonframework:
        axonserver:
          connector:
            event:
              axon:
                AxonServerEventStore: DEBUG
